server:
  port: 9001
# spring beans
spring:
  application:
    name: user-auth
  redis:
    host: 192.168.77.150
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.77.150:3306/changgou_oauth?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
# registry
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
# oauth2
auth:
  ttl: 3600 # duration time in redis
  clientId: shop
  clientDomain: localhost
  clientSecret: shop
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/shop.jks
    secret: shopshop
    alias: shop
    password: shopshop