server:
  port: 18086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
ribbon:
  ReadTimeout: 300000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000
          strategy: SEMAPHORE
spring:
  thymeleaf:
    cache: false
#    encoding: UTF-8
#    mode:
#    prefix: classpath:/templates/
#    suffix: .html
  application:
    name: search-web
  main:
    allow-bean-definition-overriding: true