server:
  port: 18091
spring:
  application:
    name: seckill
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.77.150:3306/changgou_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  rabbitmq:
    host: 192.168.77.150
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.77.150
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
          strategy: SEMAPHORE
logging:
  level:
    com:
      shop:
        seckill:
          dao: info
# customized message queue and exchange config
mq:
  pay:
    exchange:
      seckillorder: exchange.seckillorder
    queue:
      seckillorder: queue.seckillorder
    routing:
      seckillkey: queue.seckillorder